name: aula9
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.3.1
  dio: ^4.0.4
  localization: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7
  modular_test: ^1.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/lang2/
